## Innomatics Internship APR 21
### Week 4 - Task - 6
###### AUTHOR : MOHIT KUMAR
###### EMAIL : mohitkrs848@gmail.com

In [17]:
#Question 1 : Arrays

import numpy

def arrays(arr):
    a = numpy.array(arr,float)
    return numpy.flip(a)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [18]:
#Question 2 : Shape and Reshape

import numpy
arr= input().split(' ')
np_arr= numpy.array(arr,int)
print(numpy.reshape(np_arr,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#Question 3 : Transpose and Flatten

import numpy

N, M = map(int,input().split())
ele = numpy.array([input().strip().split() for i in range(N)], int)

print(ele.transpose())
print(ele.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [5]:
### Question 4 : Concatenate

import numpy

N,M,P = map(int,input().split())
arr1 = numpy.array([input().split() for i in range(N)],int)
arr2 = numpy.array([input().split() for i in range(M)],int)

print(numpy.concatenate((arr1,arr2), axis = 0))

4 3 2
1 2 
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [6]:
#Question 5 : Zeros and Ones

import numpy

N = list(map(int,input().split()))
print(numpy.zeros(N,int))
print(numpy.ones(N,int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [7]:
#Question 6 : Eye and Identity

import numpy
numpy.set_printoptions(legacy='1.13')

N, M = map(int,input().split())
print(numpy.eye(N, M, k = 0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [8]:
#Question 7 : Array Mathematics

import numpy
import numpy

N,M=map(int,input().split())

A=numpy.array([list(map(int,input().split())) for n in range(N)])
B=numpy.array([list(map(int,input().split())) for n in range(N)])

print(numpy.add(A,B))
print(numpy.subtract(A,B))
print(numpy.multiply(A,B))
m=A/B
print(numpy.int_(m))
print(numpy.mod(A,B))
print(numpy.power(A,B))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [9]:
#Question 8 : Floor, Ceil and Rint

import numpy
numpy.set_printoptions(legacy = '1.13')

A = numpy.array(input().split(),float)

print(numpy.floor(A))
print(numpy.ceil(A))
print(numpy.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [10]:
#Question 9 : Sum and Prod

import numpy

N,M = map(int,input().split())
A = numpy.array([input().split() for i in range(N)], int)
print(numpy.prod(numpy.sum(A, axis = 0)))

2 2
1 2
3 4
24


In [11]:
#Question 10 : Min and Max

import numpy

N, M = map(int, input().split())
arr = numpy.array([input().split() for i in range(N)],int)
print(numpy.max(numpy.min(arr,axis=1)))


4 2
2 5
3 7
1 3
4 0
3


In [12]:
#Question 11 : Mean, Var, and Std

import numpy

N, M = map(int,input().split())
my_array = numpy.array([input().split() for i in range(N)],int)

print(numpy.mean(my_array, axis = 1))
print(numpy.var(my_array, axis = 0))
print(round(numpy.std(my_array,axis=None),11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [13]:
#Question 12 : Dot and Cross

import numpy

N = int(input())
A = numpy.array([input().split() for i in range(N)],int)
B = numpy.array([input().split() for i in range(N)],int)

print(numpy.dot(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [14]:
#Question 13 : Inner and Outer

import numpy

A = numpy.array(input().split(), int)
B = numpy.array(input().split(), int)

print(numpy.inner(A, B))
print(numpy.outer(A, B))

0 1
2 3
3
[[0 0]
 [2 3]]


In [15]:
#Question 14 : Polynomials

import numpy

p = numpy.array(input().split(),float)
x = int(input())

print(numpy.polyval(p,x))

1.1 2 3
0
3.0


In [16]:
#Question 15 : Linear Algebra

import numpy

N = int(input())
A = numpy.array([input().split() for i in range(N)],float)

print(round(numpy.linalg.det(A),2))

2
1.1 1.1
1.1 1.1
0.0
